# Название проекта
name: BankingDemo
options:
  # Версия Xcode
  xcodeVersion: 11.3.1
  # Создание пустых директорий
  generateEmptyDirectories: true
  # Создание групп
  createIntermediateGroups: true
targets:
    # Teстовый таргет
    UnitTests:
      type: bundle.unit-test
      platform: iOS
      deploymentTarget: 11.0
      scheme:
        configVariants: all
      sources: [UnitTests]
      info:
        path: UnitTests/Info.plist
        properties: []
      dependencies:
        - target: BankingDemoRelease
    # Debug таргет
    BankingDemoDebug:
      type: application
      platform: iOS
      deploymentTarget: 11.0
      scheme:
        configVariants: all
        testTargets: [UnitTests]
      sources: 
        - path: BankingDemo
      info:
        path: BankingDemo/Application/Info/Debug/Info.plist
        properties:
          CFBundleName: BankingDemoDebug
          UILaunchStoryboardName: LaunchScreen
      settings:
        base:
          PRODUCT_BUNDLE_IDENTIFIER: ru.surfstudio.bankingdemo.debug
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Debug
      preBuildScripts:
        - script: ${SRCROOT}/Pods/SwiftGen/bin/swiftgen
          name: SwiftGen
      postCompileScripts:
        - script: ${SRCROOT}/Pods/SwiftLint/swiftlint --config "${SRCROOT}/.swiftlint.yml"
          name: Swiftlint
    # Release target
    BankingDemoRelease:
      type: application
      platform: iOS
      deploymentTarget: 11.0
      scheme:
        configVariants: all
        testTargets: [UnitTests]
      sources: 
        - path: BankingDemo
      info:
        path: BankingDemo/Application/Info/Release/Info.plist
        properties:
          CFBundleName: BankingDemoRelease
          UILaunchStoryboardName: LaunchScreen
      settings:
        base:
          PRODUCT_BUNDLE_IDENTIFIER: ru.surfstudio.bankingdemo.release
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      preBuildScripts:
        - script: ${SRCROOT}/Pods/SwiftGen/bin/swiftgen
          name: SwiftGen
      postCompileScripts:
        - script: ${SRCROOT}/Pods/SwiftLint/swiftlint --config "${SRCROOT}/.swiftlint.yml"
          name: Swiftlint
